if &compatible
    set nocompatible
endif

let $VIM_PATH = expand('$HOME/.vim')

source $VIM_PATH/rc.d/0_1_install_plug.init

source $VIM_PATH/rc.d/0_2_load_plugins.init

source $VIM_PATH/rc.d/0_3_install_plugins.init

" Load runtime configuration files
for g:rc in split(glob('$VIM_PATH/rc.d/*.vim'), '\n')
  exec 'source' rc
endfor
