#!/usr/bin/env sh

yabai -m config layout                       bsp

yabai -m config window_gap                   10
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
# yabai -m config focus_follows_mouse autoraise
# yabai -m config mouse_follows_focus on

yabai -m rule --add app="^System Preferences$"                    manage=off
yabai -m rule --add app="^System Settings$"                       manage=off
yabai -m rule --add app="^System Information$"                    manage=off
# yabai -m rule --add app="^Finder$" title="(Info|Preferences)"     manage=off
yabai -m rule --add app="^Finder$"                                manage=off
yabai -m rule --add app="^Calculator$"                            manage=off
yabai -m rule --add app="^Activity Monitor$"                      manage=off
yabai -m rule --add app="^Font Book$"                             manage=off
yabai -m rule --add app="^Archive Utility$"                       manage=off
yabai -m rule --add label="App Store" app="^App Store$"           manage=off
yabai -m rule --add app="^Installer$"                             manage=off
yabai -m rule --add app="^Messenger$"                             manage=off
yabai -m rule --add app="^Raycast$"                               manage=off

# auto goes to correct spaces
# 1. web
# yabai -m rule --add app="^Arc$"              space=^1

# 2. term
yabai -m rule --add app="^kitty$"            space=^2
yabai -m rule --add app="^WezTerm$"          space=^2
yabai -m rule --add app="^wezterm-gui$"      space=^2
yabai -m rule --add app="^iTerm2$"           space=^2

# 3. editor
yabai -m rule --add app="^Code$"             space=^3
yabai -m rule --add app="^Code - Insiders$"  space=^3

# 4. Dev Tools
yabai -m rule --add app="^NoSQLBooster for MongoDB$" space=^4
yabai -m rule --add app="^Postman$"                  space=^4

# 5. float
yabai -m config --space 5 layout float

# 6. Notes
yabai -m rule --add app="^Obsidian$"            space=^6

# 7. Slack
yabai -m rule --add app="^Slack$"            space=^7

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
