#!/usr/bin/env sh

yabai -m config layout                       bsp

yabai -m config window_gap                   10
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on

yabai -m rule --add app="^System Preferences$"                    manage=off
yabai -m rule --add app="^System Information$"                    manage=off
# yabai -m rule --add app="^Finder$" title="(Info|Preferences)"     manage=off
yabai -m rule --add app="^Finder$"                                manage=off
yabai -m rule --add app="^Calculator$"                            manage=off
yabai -m rule --add app="^Activity Monitor$"                      manage=off
yabai -m rule --add app="^Font Book$"                             manage=off
yabai -m rule --add app="^Archive Utility$"                       manage=off
yabai -m rule --add label="App Store" app="^App Store$"           manage=off
yabai -m rule --add app="^Installer$"                             manage=off
