#!/bin/sh

bspc config external_rules_command "$(dirname $0)/external_rules"

if xrandr | grep "DP2 connected"; then
  bspc monitor DP2 -d web term editor calendar others
  bspc monitor eDP1 -d web
else
  bspc monitor eDP1 -d web term editor calendar others
fi


bspc config -m ^1 border_width  2
bspc config -m ^2 border_width  2

bspc config window_gap 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer   true
bspc config pointer_follows _focus  true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Auto flag
# Mini Ranger File Manager Window
bspc rule -a floating_ranger_fm state=floating rectangle=800x500+560+290

# No border ulauncher
bspc rule -a ulauncher border=off

# Oneko always on top
# bspc rule -a "oneko" layer=above

# Auto swap in correct workspace
# Terminal
bspc rule -a kitty desktop='^2' follow=on

# Editor
bspc rule -a code-oss desktop='^3' follow=on

# wallpaper
feh --bg-fill --randomize ~/.wallpapers/*

#bar
polybar-launch &

# put this to visudo
# %wheel ALL=NOPASSWD: /usr/bin/xkeysnail
sudo /usr/bin/xkeysnail --quiet --watch ~/.config/kinto/kinto.py &

compton &
dunst &
# ulauncher --hide-window &
start-oneko &
