#!/bin/sh

wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")
echo -ne "id $wid\nclass $class\ninst $instance\ntitle $title\n" >> /tmp/extout

case "$instance" in
    ulauncher)
        if [ "$title" = "Ulauncher Preferences" ]; then
          echo "state=floating"
        fi
        echo "border=off"
        ;;
    mpd_cava)
        echo "floating = on"
        xdotool windowmove $wid 0 0
        ;;
    floating_ranger)
        echo "floating = on"
        ;;
    gsimplecal)
        echo "border=off sticky=on focus=off locked=on"
        xdotool windowmove $wid 3600 24
        ;;
esac

